# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the doc/ directory with Sphinx
sphinx:
   configuration: doc/conf.py
   fail_on_warning: true

# Set the version of Python and requirements required to build the docs.
python:
   version: 3.8
   install:
      # Install pymongo itself.
      - method: pip
        path: .
      - requirements: doc/docs-requirements.txt
