mode = "local"
project = ""
shell = ""

[dirs]
project = []
python = "isolated"
data = "/Users/steve.silvester/workspace/mongo-python-driver/.hatch/data"
cache = "/Users/steve.silvester/workspace/mongo-python-driver/.hatch/cache"

[dirs.env]



[projects]

[publish.index]
repo = "main"

[template]
name = "Steven Silvester"
email = "steve.silvester@mongodb.com"

[template.licenses]
headers = true
default = [
    "MIT",
]

[template.plugins.default]
tests = true
ci = false
src-layout = true

[terminal.styles]
info = "bold"
success = "bold cyan"
error = "bold red"
warning = "bold yellow"
waiting = "bold magenta"
debug = "bold"
spinner = "simpleDotsScrolling"
