# Stubs for bson.codec_options (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import datetime
from typing import Any, NamedTuple, Optional

_options_base = NamedTuple('_options_base', [
    ('document_class', type),
    ('tz_aware', bool),
    ('uuid_representation', int),
    ('unicode_decode_error_handler', str),
    ('tzinfo', datetime.tzinfo),
])

class CodecOptions(_options_base):
    def __new__(
        cls,
        document_class: type = ...,
        tz_aware: bool = ...,
        uuid_representation: int = ...,
        unicode_decode_error_handler: str = ...,
        tzinfo: Optional[datetime.tzinfo] = ...) -> CodecOptions: ...
    def with_options(self, **kwargs: Any) -> CodecOptions: ...

DEFAULT_CODEC_OPTIONS: CodecOptions = ...
