# Stubs for bson.tz_util (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from datetime import datetime, timedelta, tzinfo
from typing import Optional, Tuple, Union

ZERO: timedelta

class FixedOffset(tzinfo):
    def __init__(self, offset: Union[float, timedelta], name: str) -> None: ...
    def __getinitargs__(self) -> Tuple[timedelta, str]: ...
    def utcoffset(self, dt: Optional[datetime]) -> timedelta: ...
    def tzname(self, dt: Optional[datetime]) -> str: ...
    def dst(self, dt: Optional[datetime]) -> timedelta: ...

utc: FixedOffset
