ASCENDING: int = ...
DESCENDING: int = ...
GEO2D: str = ...
GEOHAYSTACK: str = ...
GEOSPHERE: str = ...
HASHED: str = ...
TEXT: str = ...
OFF: int = ...
SLOW_ONLY: int = ...
ALL: int = ...
version_tuple = (3, 5, 0, '.dev0')


def get_version_string() -> str: ...


__version__ = version = ...

from pymongo.collection import ReturnDocument
from pymongo.common import (MIN_SUPPORTED_WIRE_VERSION,
                            MAX_SUPPORTED_WIRE_VERSION)
from pymongo.cursor import CursorType
from pymongo.mongo_client import MongoClient
from pymongo.mongo_replica_set_client import MongoReplicaSetClient
from pymongo.operations import (IndexModel,
                                InsertOne,
                                DeleteOne,
                                DeleteMany,
                                UpdateOne,
                                UpdateMany,
                                ReplaceOne)
from pymongo.read_preferences import ReadPreference
from pymongo.write_concern import WriteConcern

def has_c() -> bool: ...
