from typing import Any, Dict, Optional, Tuple

from bson.codec_options import CodecOptions
from pymongo.auth import MongoCredential
from pymongo.pool import PoolOptions
from pymongo.read_concern import ReadConcern
from pymongo.read_preferences import _ServerMode
from pymongo.ssl_support import SSLContext
from pymongo.write_concern import WriteConcern


class ClientOptions(object):
    def __init__(self, username: str, password: str, database: str, options: Dict[str, Any]) -> None: ...
    @property
    def connect(self) -> bool: ...
    @property
    def codec_options(self) -> CodecOptions: ...
    @property
    def credentials(self) -> MongoCredential: ...
    @property
    def local_threshold_ms(self) -> int: ...
    @property
    def server_selection_timeout(self) -> int: ...
    @property
    def heartbeat_frequency(self) -> int: ...
    @property
    def pool_options(self) -> PoolOptions: ...
    @property
    def read_preference(self) -> _ServerMode: ...
    @property
    def replica_set_name(self) -> Optional[str]: ...
    @property
    def write_concern(self) -> WriteConcern: ...
    @property
    def read_concern(self) -> ReadConcern: ...
