from typing import Any, Callable, Dict, List, Mapping, Optional, Sequence, Union

from bson import CodecOptions, DBRef
from bson.timestamp import Timestamp
from pymongo import MongoClient, common
from pymongo.change_stream import DatabaseChangeStream
from pymongo.client_session import ClientSession
from pymongo.collation import Collation
from pymongo.collection import Collection
from pymongo.command_cursor import CommandCursor
from pymongo.pool import SocketInfo
from pymongo.read_concern import ReadConcern
from pymongo.read_preferences import _ServerMode
from pymongo.son_manipulator import SONManipulator
from pymongo.write_concern import WriteConcern


class Database(common.BaseObject):
    def __init__(
        self,
        client: MongoClient,
        name: str,
        codec_options: Optional[CodecOptions] = ...,
        read_preference: Optional[_ServerMode] = ...,
        write_concern: Optional[WriteConcern] = ...,
        read_concern: Optional[ReadConcern] = ...) -> None: ...
    def add_son_manipulator(self, manipulator: SONManipulator) -> None: ...
    @property
    def system_js(self) -> SystemJS: ...
    @property
    def client(self) -> MongoClient: ...
    @property
    def name(self) -> str: ...
    @property
    def incoming_manipulators(self) -> List[str]: ...
    @property
    def incoming_copying_manipulators(self) -> List[str]: ...
    @property
    def outgoing_manipulators(self) -> List[str]: ...
    @property
    def outgoing_copying_manipulators(self) -> List[str]: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __getattr__(self, name: str) -> Collection: ...
    def __getitem__(self, name: str) -> Collection: ...
    def get_collection(
        self,
        name: str,
        codec_options: Optional[CodecOptions] = ...,
        read_preference: Optional[_ServerMode] = ...,
        write_concern: Optional[WriteConcern] = ...,
        read_concern: Optional[ReadConcern] = ...) -> Collection: ...
    def create_collection(
        self,
        name: str,
        codec_options: Optional[CodecOptions] = ...,
        read_preference: Optional[_ServerMode] = ...,
        write_concern: Optional[WriteConcern] = ...,
        read_concern: Optional[ReadConcern] = ...,
        session: Optional[ClientSession] = ...,
        **kwargs: Any) -> Collection: ...
    def watch(
        self,
        pipeline: Optional[Sequence[Mapping[str, Any]]],
        full_document: str = ...,
        resume_after: Optional[str] = ...,
        max_await_time_ms: Optional[int] = ...,
        batch_size: Optional[int] = ...,
        collation: Optional[Collation] = ...,
        start_at_operation_time: Optional[Timestamp] = ...,
        session: Optional[ClientSession] = ...) -> DatabaseChangeStream: ...
    def command(
        self,
        command: Union[str, Mapping[str, Any]],
        value: int = ...,
        check: bool = ...,
        allowable_errors: Optional[Sequence[str]] = ...,
        read_preference: _ServerMode = ...,
        codec_options: CodecOptions = ...,
        session: Optional[ClientSession] = ...,
        **kwargs: Any) -> Any: ...
    def list_collections(self, session: Optional[ClientSession] = ..., **kwargs: Any) -> CommandCursor: ...
    def list_collection_names(self, session: Optional[ClientSession] = ...) -> List[str]: ...
    def collection_names(self, include_system_collections: bool = ..., session: Optional[ClientSession] = ...) -> List[str]: ...
    def drop_collection(
        self,
        name_or_collection: Union[str, Collection],
        session: Optional[ClientSession]  = ...) -> Dict[str, Any]: ...
    def validate_collection(
        self,
        name_or_collection: Union[str, Collection],
        scandata: bool = ...,
        full: bool = ...,
        session: Optional[ClientSession] = ...) -> Dict[str, Any]: ...
    def current_op(self, include_all: bool = ..., session: Optional[ClientSession] = ...) -> Dict[str, Any]: ...
    def profiling_level(self, session: Optional[ClientSession] = ...) -> int: ...
    def set_profiling_level(self, level: int, slow_ms: Optional[int] = ..., session: Optional[ClientSession] = ...) -> None: ...
    def profiling_info(self, session: Optional[ClientSession] = ...) -> List[Any]: ...
    def error(self) -> Any: ...
    def last_status(self) -> Any: ...
    def previous_error(self) -> Any: ...
    def reset_error_history(self) -> None: ...
    def __iter__(self) -> 'Database': ...
    def __next__(self) -> None: ...
    def add_user(
        self,
        name: str,
        password: Optional[str] = ...,
        read_only: Optional[bool] = ...,
        session: Optional[ClientSession] = ...,
        **kwargs: Any) -> None: ...
    def remove_user(self, name: str, session: Optional[ClientSession] = ...) -> None: ...
    def authenticate(
        self,
        name: Optional[str] = ...,
        password: Optional[str] = ...,
        source: Optional[str] = ...,
        mechanism: str = ...,
        **kwargs: Any) -> bool: ...
    def logout(self) -> None: ...
    def dereference(self, dbref: DBRef, session: Optional[ClientSession] = ..., **kwargs: Any) -> Dict[str, Any]: ...
    def eval(self, code: str, *args: Any) -> Any: ...

class SystemJS(object):
    def __init__(self, database: Database) -> None: ...
    def __setattr__(self, name: str, code: str) -> None: ...
    def __setitem__(self, name: str, code: str) -> None: ...
    def __delattr__(self, name: str) -> None: ...
    def __delitem__(self, name: str) -> None: ...
    def __getattr__(self, name: str) -> Callable[..., Any]: ...
    def __getitem__(self, name: str) -> Callable[..., Any]: ...
    def list(self) -> List[str]: ...
