from typing import Any, Dict, List, Mapping, Optional, Tuple


class IsMaster(object):
    def __init__(self, doc: Mapping[str, Any]) -> None: ...
    @property
    def document(self) -> Dict[str, Any]: ...
    @property
    def server_type(self) -> int: ...
    @property
    def all_hosts(self) -> List[Any]: ...
    @property
    def tags(self) -> Dict[str, Any]: ...
    @property
    def primary(self) -> Optional[Tuple[str, int]]: ...
    @property
    def replica_set_name(self) -> Optional[str]: ...
    @property
    def max_bson_size(self) -> int: ...
    @property
    def max_message_size(self) -> int: ...
    @property
    def max_write_batch_size(self) -> int: ...
    @property
    def min_wire_version(self) -> int: ...
    @property
    def max_wire_version(self) -> int: ...
    @property
    def set_version(self) -> Any: ...
    @property
    def election_id(self) -> Any: ...
    @property
    def is_writable(self) -> bool: ...
    @property
    def is_readable(self) -> bool: ...
    @property
    def me(self) -> Optional[Tuple[str, int]]: ...
    @property
    def last_write_date(self) -> Any: ...
