from pymongo.server_selectors import Selection


IDLE_WRITE_PERIOD: int = ...
SMALLEST_MAX_STALENESS: int = ...
def _validate_max_staleness(max_staleness: int, heartbeat_frequency: int) -> None: ...
def _with_primary(max_staleness: int, selection: Selection) -> Selection: ...
def _no_primary(max_staleness: int, selection: Selection) -> Selection: ...
def select(max_staleness: int, selection: Selection) -> Selection: ...
