import threading
from typing import Dict, List, Optional, Sequence, Tuple

from pymongo.monitor import Monitor
from pymongo.pool import Pool, PoolOptions
from pymongo.server_description import ServerDescription


class TopologySettings(object):
    def __init__(self, seeds: Optional[Sequence[Tuple[str, int]]] = ..., replica_set_name: Optional[str] = ..., pool_class: Optional[Pool] = ..., pool_options: Optional[PoolOptions] = ..., monitor_class: Optional[Monitor] = ..., condition_class: Optional[threading.Condition] = ..., local_threshold_ms: int = ..., server_selection_timeout: int = ..., heartbeat_frequency: int = ...) -> None: ...
    @property
    def seeds(self) -> List[Tuple[str, int]]: ...
    @property
    def replica_set_name(self) -> str: ...
    @property
    def pool_class(self) -> Pool: ...
    @property
    def pool_options(self) -> PoolOptions: ...
    @property
    def monitor_class(self) -> Monitor: ...
    @property
    def condition_class(self) -> threading.Condition: ...
    @property
    def local_threshold_ms(self) -> int: ...
    @property
    def server_selection_timeout(self) -> int: ...
    @property
    def heartbeat_frequency(self) -> int: ...
    @property
    def direct(self) -> bool: ...
    def get_topology_type(self) -> int: ...
    def get_server_descriptions(self) -> Dict[Tuple[str, int], ServerDescription]: ...
