from typing import Any, Optional, Union
from pymongo.ssl_context import SSLContext as SSLContext

HAVE_SSL: bool = ...

def validate_cert_reqs(option: str, value: Optional[Union[str, int]]) -> Any: ...
def get_ssl_context(*args: Any) -> Any: ...
