#!/usr/bin/env bash
set -eux

npm install -g m

pip install git+https://github.com/blink1073/mtools@pymongo-4

pip install -e ".[srv]"

cd binder

yes | m $(cat VERSION)

m

wget https://atlas-education-staging.s3.amazonaws.com/sampledata.archive.gz

VERSION=`cat VERSION`
PORT=`cat PORT`
MONGODB_BIN=`m bin $VERSION`
cmd="mlaunch init --replicaset --name repl0 --nodes 3 --binarypath \
$MONGODB_BIN --port $PORT --hostname localhost --setParameter \
enableTestCommands=1"
echo $cmd
eval $cmd

mongorestore --gzip --archive=sampledata.archive.gz
rm sampledata.archive.gz

mlaunch kill