#!/usr/bin/env bash
set -eux

pushd binder

PORT=`cat PORT`
VERSION=`cat VERSION`

# Install `m`` and a local mongod server.
npm install -g m
yes | m $VERSION
m

# Launch a replicaset using `mlaunch``.
bash ./init

# Download sample data and add content to the database.
wget https://atlas-education-staging.s3.amazonaws.com/sampledata.archive.gz
mongorestore --host repl0/localhost:$PORT --nsInclude="sample_mflix.*" --gzip --archive=sampledata.archive.gz
rm sampledata.archive.gz

# Kill the server (we will restart it with the existing data during launch).
mlaunch kill

popd

# Install ourselves
pip install -e ".[srv]"
