#!/usr/bin/env bash
set -eux

pushd binder

# Install `m`` and a local mongod server.
npm install -g m
yes | m $(cat VERSION)
m

# Launch a replicaset using `mlaunch``.
VERSION=`cat VERSION`
PORT=`cat PORT`
MONGODB_BIN=`m bin $VERSION`
cmd="mlaunch init --replicaset --name repl0 --nodes 3 --binarypath \
$MONGODB_BIN --priority --port $PORT --hostname localhost --setParameter \
enableTestCommands=1"
echo $cmd
eval $cmd

# Download sample data and add content to the database.
wget https://atlas-education-staging.s3.amazonaws.com/sampledata.archive.gz
mongorestore --host repl0/localhost:$PORT --nsInclude="sample_mflix.*" --gzip --archive=sampledata.archive.gz
rm sampledata.archive.gz

# Kill the server (we will restart it with the existing data during launch).
mlaunch kill

popd

# Install ourselves
pip install -e ".[srv]"