#!/usr/bin/env python3
import sys
import shutil
import os
import subprocess

HERE = os.path.abspath(os.path.dirname(__file__))

# Start the mongo server again
subprocess.check_call(["mlaunch", "start"], cwd=HERE)

# Launch Jupyter
argv = sys.argv[1:]
print(argv)
os.execv(shutil.which(argv[0]), argv)