#!/usr/bin/env python3
import sys
import shutil
import os
import subprocess

# Start the local mongodb as a background task
binder_folder = os.path.join(os.getcwd(), 'binder')
subprocess.run(['init'], shell=True, cwd=binder_folder)

# Launch Jupyter
argv = sys.argv[1:]
print(argv)
os.execv(shutil.which(argv[0]), argv)